# man_hours: 1.4
"""Build the baseline-vs-EPRI weight delta artefact for SP-B.

Reads ``config/scoring_rubrics/`` (the loud-fail-canonical rubric directory),
normalises composite weights under both ``baseline`` and ``epri`` bases, and
writes a side-by-side comparison to
``audit/post_processing/epri_weights/``:

- ``baseline_vs_epri.csv`` - one row per composite-participating criterion.
- ``baseline_vs_epri.md`` - human-readable table with category roll-ups.
- ``basis_resolution.json`` - per-criterion ``(weight_factor, basis_used)``
  tuples for downstream provenance rendering (FB-LL-09 bullet output).

Run from the repo root::

    PYTHONPATH=src python src/scripts/build_epri_weights_artefact.py
"""

from __future__ import annotations

import csv
import datetime as dt
import json
from collections import defaultdict
from pathlib import Path

from atoms_vs_ashes.scoring.rubric import (
    Criterion,
    load_rubric_bundle,
    weight_basis_resolution,
    weight_normalisation,
)

REPO = Path(__file__).resolve().parents[2]
RUBRIC_DIR = REPO / "config" / "scoring_rubrics"
OUT_DIR = REPO / "audit" / "post_processing" / "epri_weights"

FAMILY_LABEL = {
    "bf": "Basic filters (BF)",
    "nh": "Natural hazards (NH)",
    "hi": "Human-induced (HI)",
    "ri": "Radiological impact (RI)",
    "ep": "Emergency planning (EP)",
    "ns": "Non-safety (NS)",
}


def _participates_summary(bundle: dict[str, Criterion]) -> tuple[list[str], list[str]]:
    composite = sorted(cid for cid, c in bundle.items() if c.participates_in_composite)
    gated = sorted(cid for cid, c in bundle.items() if not c.participates_in_composite)
    return composite, gated


def write_csv(
    path: Path,
    bundle: dict[str, Criterion],
    baseline: dict[str, float],
    epri: dict[str, float],
    resolution: dict[str, tuple[int, str]],
) -> None:
    composite, _ = _participates_summary(bundle)
    with path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(
            [
                "criterion_id",
                "name",
                "family",
                "baseline_factor",
                "epri_factor",
                "basis_used",
                "baseline_pct",
                "epri_pct",
                "delta_pct",
            ]
        )
        for cid in composite:
            c = bundle[cid]
            factor_epri, basis_used = resolution[cid]
            b = baseline[cid] * 100
            e = epri[cid] * 100
            w.writerow(
                [
                    cid,
                    c.name,
                    c.family.upper(),
                    c.weight_factor,
                    factor_epri,
                    basis_used,
                    f"{b:.4f}",
                    f"{e:.4f}",
                    f"{e - b:+.4f}",
                ]
            )


def write_markdown(
    path: Path,
    bundle: dict[str, Criterion],
    baseline: dict[str, float],
    epri: dict[str, float],
    resolution: dict[str, tuple[int, str]],
) -> None:
    composite, gated = _participates_summary(bundle)
    lines: list[str] = []
    lines.append("<!-- man_hours: 1.0 -->\n")
    lines.append("# Baseline-vs-EPRI weight delta (SP-B)\n")
    lines.append(
        f"_Generated by `src/scripts/build_epri_weights_artefact.py` "
        f"on {dt.datetime.now().isoformat(timespec='seconds')}._\n"
    )
    lines.append(
        "Per-criterion normalised weight under the project **baseline** weight "
        "basis vs the **EPRI / IAEA SSG-35** basis defined in "
        "`config/epri/weights.yaml`. The composite denominator is the sum of "
        "integer `weight_factor` values for criteria that participate in the "
        "ranking composite (exclusionary-gated criteria contribute weight on "
        "their gate but not on the composite). Both columns sum to 100 % "
        "across composite-participating criteria.\n"
    )
    lines.append(f"- Composite criteria: **{len(composite)}**\n")
    lines.append(
        f"- Exclusionary-gated criteria (carried in rubric for provenance "
        f"only): **{len(gated)}** ({', '.join(gated)})\n"
    )
    lines.append("\n## Per-criterion delta\n")
    lines.append(
        "| ID | Family | Name | Baseline factor | EPRI factor | Basis used | Baseline % | EPRI % | Δ (EPRI - baseline) |\n"
    )
    lines.append(
        "| --- | --- | --- | ---: | ---: | --- | ---: | ---: | ---: |\n"
    )
    for cid in composite:
        c = bundle[cid]
        epri_f, basis_used = resolution[cid]
        b = baseline[cid] * 100
        e = epri[cid] * 100
        delta = e - b
        lines.append(
            f"| {cid} | {c.family.upper()} | {c.name} | "
            f"{c.weight_factor} | {epri_f} | {basis_used} | "
            f"{b:.3f} | {e:.3f} | {delta:+.3f} |\n"
        )

    fam_baseline: dict[str, float] = defaultdict(float)
    fam_epri: dict[str, float] = defaultdict(float)
    for cid in composite:
        c = bundle[cid]
        fam_baseline[c.family] += baseline[cid] * 100
        fam_epri[c.family] += epri[cid] * 100
    lines.append("\n## Family roll-ups (composite share)\n")
    lines.append("| Family | Baseline % | EPRI % | Δ |\n")
    lines.append("| --- | ---: | ---: | ---: |\n")
    total_b = sum(fam_baseline.values())
    total_e = sum(fam_epri.values())
    for fam in ("bf", "nh", "hi", "ri", "ep", "ns"):
        if fam not in fam_baseline:
            continue
        b = fam_baseline[fam]
        e = fam_epri[fam]
        lines.append(
            f"| {FAMILY_LABEL[fam]} | {b:.2f} | {e:.2f} | {e - b:+.2f} |\n"
        )
    lines.append(
        f"| **Total** | **{total_b:.2f}** | **{total_e:.2f}** | "
        f"**{total_e - total_b:+.2f}** |\n"
    )

    lines.append("\n## Notes\n")
    lines.append(
        "- The EPRI integer factors are derived from the percent values in "
        "`docs/expert_siting_criteria_evaluation_matrix.md` Summary table via "
        "`round(weight_pct × 10 / 4.7)`, transcribed into "
        "`config/epri/weights.yaml`. Re-running this script after editing the "
        "rubric YAMLs is the canonical way to refresh this report.\n"
    )
    lines.append(
        "- The renderer reads `weight_basis_resolution(bundle, basis='epri')` "
        "to print `weight 0.XXXX (basis: epri)` per criterion bullet (FB-LL-09 "
        "weight-provenance acceptance).\n"
    )
    path.write_text("".join(lines))


def write_json(
    path: Path,
    bundle: dict[str, Criterion],
    baseline: dict[str, float],
    epri: dict[str, float],
    resolution: dict[str, tuple[int, str]],
) -> None:
    payload = {
        "generated_at": dt.datetime.now().isoformat(timespec="seconds"),
        "rubric_dir": str(RUBRIC_DIR.relative_to(REPO)),
        "criteria": {
            cid: {
                "name": bundle[cid].name,
                "family": bundle[cid].family.upper(),
                "baseline_factor": bundle[cid].weight_factor,
                "epri_factor": resolution[cid][0],
                "basis_used": resolution[cid][1],
                "baseline_pct": round(baseline[cid] * 100, 6),
                "epri_pct": round(epri[cid] * 100, 6),
            }
            for cid in sorted(baseline)
        },
    }
    path.write_text(json.dumps(payload, indent=2))


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    bundle = load_rubric_bundle(str(RUBRIC_DIR))
    baseline = weight_normalisation(bundle, basis="baseline")
    epri = weight_normalisation(bundle, basis="epri")
    resolution = weight_basis_resolution(bundle, basis="epri")

    csv_path = OUT_DIR / "baseline_vs_epri.csv"
    md_path = OUT_DIR / "baseline_vs_epri.md"
    json_path = OUT_DIR / "basis_resolution.json"

    write_csv(csv_path, bundle, baseline, epri, resolution)
    write_markdown(md_path, bundle, baseline, epri, resolution)
    write_json(json_path, bundle, baseline, epri, resolution)

    print(f"Wrote {csv_path.relative_to(REPO)}")
    print(f"Wrote {md_path.relative_to(REPO)}")
    print(f"Wrote {json_path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
