# man_hours: 2.0
"""Scan the repo for files >= 2 MiB and emit a manifest (stdout or docs/large_assets.md).

Skips `.git`, `.venv`, `__pycache__`, and common build dirs. Used to maintain
`docs/large_assets.md` and to validate `.gitignore` coverage.

Usage:
    python src/scripts/list_large_files.py
    python src/scripts/list_large_files.py --min-mb 2 --write-doc
    python src/scripts/list_large_files.py --verify
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

MIN_BYTES_DEFAULT = 2 * 1024 * 1024  # 2 MiB

SKIP_DIR_NAMES = frozenset({
    ".git", ".venv", "venv", "venv_test", "__pycache__", ".pytest_cache",
    "node_modules", ".mypy_cache", ".ruff_cache", "dist", "build",
})

# Repo root (this file lives at src/scripts/list_large_files.py).
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DOC_PATH = PROJECT_ROOT / "docs" / "large_assets.md"
REQUIRED_DEFAULT = PROJECT_ROOT / "docs" / "large_assets_required.txt"


def _role_for_path(rel: str) -> tuple[str, str]:
    """Return (role, obtain_hint) for documentation."""
    r = rel.replace("\\", "/")
    # Some checkouts mirror bulk data under src/data/sources/; treat like sources/.
    if r.startswith("src/data/sources/"):
        r = "sources/" + r[len("src/data/sources/") :]
    if r.startswith("sources/wdpa/"):
        return (
            "WDPA / Protected Planet geometry and indexes (S-15, NS-08 / E7).",
            "`atoms-vs-ashes enrich ingest-wdpa` (API or bulk) — see docs/api_keys.md",
        )
    if r.startswith("sources/liquefaction/"):
        return (
            "Zhu et al. global liquefaction susceptibility GeoTIFF (S-22, NH-03 / E2).",
            "`atoms-vs-ashes enrich download-liquefaction`",
        )
    if r.startswith("sources/population/ghsl/"):
        return (
            "GHSL GHS-POP population rasters (S-20, E8 / RI-04, EP-01).",
            "`atoms-vs-ashes enrich download-ghsl-pop`",
        )
    if r.startswith("sources/worldcover/"):
        return (
            "ESA WorldCover 10 m tiles (land cover / screening context).",
            "Download per tile from ESA WorldCover portal or connector cache.",
        )
    if "global_coal_plant_tracker" in r:
        return (
            "GEM Coal Plant Tracker and ownership spreadsheets (site ingest, NS-05/06/10/11).",
            "https://globalenergymonitor.org/projects/global-coal-plant-tracker/",
        )
    if r.startswith("sources/regulations/") and r.lower().endswith(".pdf"):
        return (
            "Normative PDF references (DOE/EPRI/IAEA siting guidance).",
            "Place manually under `sources/regulations/` per project research policy.",
        )
    if r.startswith("sources/seismic/"):
        return (
            "GEM global seismic raster fallback cache (S-01).",
            "Download via seismic connector / GEM documentation.",
        )
    if r.startswith("sources/entso_e/"):
        return (
            "ENTSO-E zone assessment JSON cache (S-13).",
            "Populated by `atoms-vs-ashes enrich entso-e` (requires API token).",
        )
    if r.startswith("logs/seismic/") or r.startswith("logs/entso_e/"):
        return (
            "HTTP request/response audit for connector debugging.",
            "Regenerated each connector run; safe to delete.",
        )
    if r.endswith(".zip") and "Amplasamente" in r:
        return (
            "Local bulk archive (project-specific); not required for CI.",
            "Obtain from project owner / internal share; keep outside git if preferred.",
        )
    return (
        "Large binary or cache artifact.",
        "See connector README or `docs/api_keys.md` for acquisition.",
    )


def iter_large_files(root: Path, min_bytes: int) -> list[tuple[int, Path]]:
    out: list[tuple[int, Path]] = []
    root = root.resolve()
    for dirpath, dirnames, filenames in os.walk(root, topdown=True):
        # prune
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIR_NAMES]
        dp = Path(dirpath)
        try:
            rel_parent = dp.relative_to(root)
        except ValueError:
            continue
        parts = set(rel_parent.parts)
        if parts & SKIP_DIR_NAMES:
            continue
        for name in filenames:
            p = dp / name
            try:
                st = p.stat()
            except OSError:
                continue
            if st.st_size >= min_bytes:
                out.append((st.st_size, p))
    out.sort(key=lambda x: (-x[0], str(x[1])))
    return out


def build_markdown(
    entries: list[tuple[int, Path]], min_bytes: int, root: Path,
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    min_mb = min_bytes / (1024 * 1024)
    lines: list[str] = []
    lines.append("<!-- Generated by src/scripts/list_large_files.py — do not edit the table by hand. -->\n")
    lines.append("# Large local assets (≥ {:.1f} MiB)\n\n".format(min_mb))
    lines.append(
        "These paths are **not** meant to live in git: add downloads here locally, "
        "or rely on connector caches. See [.gitignore](../.gitignore) for ignore rules.\n\n"
    )
    lines.append(f"**Manifest generated:** `{now}`  \n")
    lines.append("**Regenerate:** `python src/scripts/list_large_files.py --write-doc`\n\n")
    lines.append("---\n\n")
    lines.append("| Path | Size (MiB) | Role | How to obtain / refresh |\n")
    lines.append("| --- | ---: | --- | --- |\n")
    root = root.resolve()
    for size, path in entries:
        rel = path.relative_to(root).as_posix()
        mb = size / (1024 * 1024)
        role, obtain = _role_for_path(rel)
        lines.append(f"| `{rel}` | {mb:.2f} | {role} | {obtain} |\n")
    if not entries:
        lines.append("| *(none above threshold on this machine)* | | | |\n")
    lines.append("\n---\n\n")
    lines.append(
        "## Notes\n\n"
        "- **Git objects** under `.git/objects/` may exceed 2 MiB during fetches; "
        "they are never committed as normal files.\n"
        "- **LLM logs** under `logs/llm/` are gitignored separately (prompts and responses).\n"
        "- **Required paths** for report/analysis (optional checklist): "
        "[`docs/large_assets_required.txt`](large_assets_required.txt) — verify with "
        "`python src/scripts/list_large_files.py --verify`.\n"
        "- **Stewardship** (workflow, ignore rationale): "
        "[`docs/large_local_assets.md`](large_local_assets.md).\n"
    )
    return "".join(lines)


def load_required_paths(path: Path) -> list[str]:
    if not path.is_file():
        return []
    out: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        out.append(line.replace("\\", "/"))
    return out


def verify_required(root: Path, rel_paths: list[str]) -> list[str]:
    """Return list of required relative paths that are missing as regular files."""
    missing: list[str] = []
    for rel in rel_paths:
        p = (root / rel).resolve()
        try:
            p.relative_to(root.resolve())
        except ValueError:
            missing.append(rel)
            continue
        if not p.is_file():
            missing.append(rel)
    return missing


def main() -> int:
    ap = argparse.ArgumentParser(description="List repository files >= min size.")
    ap.add_argument("--root", type=Path, default=PROJECT_ROOT, help="Repository root")
    ap.add_argument(
        "--min-mb", type=float, default=2.0, help="Minimum file size in MiB (default: 2)",
    )
    ap.add_argument(
        "--write-doc",
        action="store_true",
        help=f"Write {DOC_PATH.relative_to(PROJECT_ROOT)}",
    )
    ap.add_argument(
        "--verify",
        action="store_true",
        help="Exit non-zero if paths listed in --required-file are missing under --root",
    )
    ap.add_argument(
        "--required-file",
        type=Path,
        default=REQUIRED_DEFAULT,
        help=f"One repo-relative path per line ({REQUIRED_DEFAULT.name} by default)",
    )
    args = ap.parse_args()
    root = args.root.resolve()
    if args.verify:
        req_path = args.required_file
        rels = load_required_paths(req_path)
        if not rels:
            print(
                f"No paths to verify ({req_path} missing or empty).",
                file=sys.stderr,
            )
            return 0
        missing = verify_required(root, rels)
        if missing:
            print("Missing required large/local assets:", file=sys.stderr)
            for m in missing:
                print(f"  {m}", file=sys.stderr)
            return 1
        print(f"All {len(rels)} required paths present.", file=sys.stderr)
        return 0
    min_bytes = int(args.min_mb * 1024 * 1024)
    entries = iter_large_files(root, min_bytes)
    md = build_markdown(entries, min_bytes, root)
    if args.write_doc:
        DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
        DOC_PATH.write_text(md, encoding="utf-8")
        print(f"Wrote {DOC_PATH}", file=sys.stderr)
    sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
