# man_hours: 0.5
"""CORINE Land Cover connector package."""

from atoms_vs_ashes.connectors.corine.client import (
    CorineConnector,
    parse_clc_features,
    extract_clc_code,
)
from atoms_vs_ashes.connectors.corine.models import (
    BatchResult,
    CLC_LABELS,
    CORINE_COVERED_COUNTRIES,
    DEFAULT_LAYER,
    DEFAULT_REST_LAYER_ID,
    DEFAULT_REST_URL,
    DEFAULT_RINGS,
    DEFAULT_WFS_URL,
    DEVELOPABLE_CODES,
    FAVOURABLE_FOOTPRINT_CLC,
    HIGH_COMBUSTIBILITY_CLC,
    LAYDOWN_SUITABLE_CLC,
    MEDIUM_COMBUSTIBILITY_CLC,
    MODERATE_FOOTPRINT_CLC,
    NATURAL_SEMINATURAL_CLC,
    NON_EU_COUNTRIES,
    RingClassification,
    SOURCE_NAME,
    SiteClassification,
    SiteEnrichmentSummary,
    UNFAVOURABLE_FOOTPRINT_CLC,
)
from atoms_vs_ashes.connectors.corine.parsers import (
    assess_buildable_adequacy,
    build_ns04_comment,
    compute_buildable_metrics,
    is_corine_covered,
)

__all__ = [
    "BatchResult",
    "CLC_LABELS",
    "CORINE_COVERED_COUNTRIES",
    "CorineConnector",
    "DEFAULT_LAYER",
    "DEFAULT_REST_LAYER_ID",
    "DEFAULT_REST_URL",
    "DEFAULT_RINGS",
    "DEFAULT_WFS_URL",
    "DEVELOPABLE_CODES",
    "FAVOURABLE_FOOTPRINT_CLC",
    "HIGH_COMBUSTIBILITY_CLC",
    "LAYDOWN_SUITABLE_CLC",
    "MEDIUM_COMBUSTIBILITY_CLC",
    "MODERATE_FOOTPRINT_CLC",
    "NATURAL_SEMINATURAL_CLC",
    "NON_EU_COUNTRIES",
    "RingClassification",
    "SOURCE_NAME",
    "SiteClassification",
    "SiteEnrichmentSummary",
    "UNFAVOURABLE_FOOTPRINT_CLC",
    "assess_buildable_adequacy",
    "build_ns04_comment",
    "compute_buildable_metrics",
    "extract_clc_code",
    "is_corine_covered",
    "parse_clc_features",
]
