# man_hours: 3.0
"""Generate audit/man_hours_summary.md from audit/man_hours_registry.yml.

Usage:
    python scripts/man_hours_report.py
    python scripts/man_hours_report.py --registry path/to/registry.yml
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = PROJECT_ROOT / "audit" / "man_hours_registry.yml"
DEFAULT_OUTPUT = PROJECT_ROOT / "audit" / "man_hours_summary.md"

CATEGORY_ORDER = [
    "Requirements & Analysis",
    "Architecture & Design",
    "Implementation",
    "Testing",
    "Database & Migrations",
    "Configuration & DevOps",
    "Research & Data Sources",
    "AI Prompts & Tooling",
    "Project Management & QA",
    "Other",
]


def load_registry(path: Path) -> dict[str, dict]:
    with open(path) as f:
        data = yaml.safe_load(f) or {}
    return data.get("files", {})


def build_report(files: dict[str, dict]) -> str:
    by_category: dict[str, list[tuple[str, float]]] = defaultdict(list)

    for fpath, info in sorted(files.items()):
        hours = float(info.get("hours", 0))
        category = info.get("category", "Other")
        by_category[category].append((fpath, hours))

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines: list[str] = []
    lines.append("<!-- man_hours: 3.0 -->\n")
    lines.append("# Man-Hours Summary\n\n")
    lines.append(f"**Generated:** {now}  \n")
    lines.append(f"**Source:** `audit/man_hours_registry.yml`\n\n")
    lines.append("---\n\n")

    lines.append("## Totals by Category\n\n")
    lines.append("| Category | Files | Hours |\n")
    lines.append("| --- | ---: | ---: |\n")

    grand_files = 0
    grand_hours = 0.0

    for cat in CATEGORY_ORDER:
        entries = by_category.get(cat, [])
        if not entries:
            continue
        cat_hours = sum(h for _, h in entries)
        lines.append(f"| {cat} | {len(entries)} | {cat_hours:.1f} |\n")
        grand_files += len(entries)
        grand_hours += cat_hours

    for cat in sorted(by_category.keys()):
        if cat not in CATEGORY_ORDER:
            entries = by_category[cat]
            cat_hours = sum(h for _, h in entries)
            lines.append(f"| {cat} | {len(entries)} | {cat_hours:.1f} |\n")
            grand_files += len(entries)
            grand_hours += cat_hours

    lines.append(f"| **Project Total** | **{grand_files}** | **{grand_hours:.1f}** |\n")
    lines.append("\n---\n\n")

    lines.append("## Detailed Breakdown\n\n")

    all_cats = [c for c in CATEGORY_ORDER if c in by_category]
    all_cats += [c for c in sorted(by_category.keys()) if c not in CATEGORY_ORDER]

    for cat in all_cats:
        entries = by_category[cat]
        entries.sort(key=lambda e: (-e[1], e[0]))
        cat_hours = sum(h for _, h in entries)

        lines.append(f"### {cat}\n\n")
        lines.append(f"**Subtotal:** {len(entries)} files, {cat_hours:.1f} hours\n\n")
        lines.append("| File | Hours |\n")
        lines.append("| --- | ---: |\n")

        for fpath, hours in entries:
            lines.append(f"| `{fpath}` | {hours:.1f} |\n")

        lines.append("\n")

    lines.append("---\n\n")
    lines.append(f"*Report generated by `scripts/man_hours_report.py` at {now}*\n")

    return "".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate man-hours summary report")
    parser.add_argument(
        "--registry", type=Path, default=DEFAULT_REGISTRY,
        help="Path to man_hours_registry.yml",
    )
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help="Path to write the summary Markdown",
    )
    args = parser.parse_args()

    files = load_registry(args.registry)
    if not files:
        print(f"No files found in {args.registry}")
        return

    report = build_report(files)
    args.output.write_text(report, encoding="utf-8")

    total = sum(float(info.get("hours", 0)) for info in files.values())
    print(f"Wrote {args.output} — {len(files)} files, {total:.1f} total hours")


if __name__ == "__main__":
    main()
